language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r test/requirements.txt"
# command to run tests
script: pytest

before_deploy:
  - ./pkg/pkgmake.sh dist
  - export PKG_FILE_ZIP=$(ls -1 ./pkg/RPMS/x86_64/*.zip 2>/dev/null)
  - export PKG_FILE_IPK=$(ls -1 ./pkg/RPMS/x86_64/*.ipk 2>/dev/null)
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - "${PKG_FILE_ZIP}"
    - "${PKG_FILE_IPK}"
  skip_cleanup: true
  on:
    tags: true