language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r test/requirements.txt"
# command to run tests
script: pytest

before_deploy:
  - ./pkg/pkgmake.sh dist
  - export PKG_FILES=$(ls -1 ./pkg/RPMS/x86_64/*.{zip,ipk,rpm} 2>/dev/null)
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: "${PKG_FILES}"
  skip_cleanup: true
  on:
    tags: true