language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r test/requirements.txt"
# command to run tests
script: pytest

before_deploy:
  - ./pkg/pkgmake.sh dist
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - ./pkg/RPMS/x86_64/artifactd-*.zip
    - ./pkg/RPMS/x86_64/artifactd-*.ipk
    - ./pkg/RPMS/x86_64/artifactd-*.rpm
  skip_cleanup: true
  on:
    tags: true